spring:
  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)  
  datasource:
    url: jdbc:mysql://192.168.3.200:3306/test
    username: root
    password: 123456
    driver-class: com.mysql.jdbc.Driver
    testWhileIdle: true 
    validationQuery: SELECT 1