spring:
  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)  
  datasource:
    url: jdbc:mysql://192.168.241.139:3306/test?useSSL=true
    username: root
    password: bndy.net 
    driver-class: com.mysql.jdbc.Driver
    testWhileIdle: true 
    validationQuery: SELECT 1